default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: <%=ENV['DATABASE_USER']%>
  password: <%=ENV['DATABASE_PASSWORD']%>
  pool: 5

development:
  <<: *default
  database: intranet_development
test:
  <<: *default
  database: intranet_test

production:
  <<: *default
  database: intranet_production
